- README.md
> Quick spelling fix 🙃

- src/input/strParse.js
- src/spacetime.js
- src/timezone/guessTz.js
1. parse string time  can pasre 2017-04-03 08:00:00-0700
2. clone method add silent of option to clone
> parse string time , clone method include "silent" clone

- package-lock.json
- package.json
fixes https://github.com/spencermountain/spacetime/issues/67
> Moves tap-spec to dev deps

- changelog.md
> prepare a commit for a proper pr

- package-lock.json
- package.json
- types/constraints.d.ts
- types/constructors.d.ts
- types/index.d.ts
- types/types.d.ts
Made documentation better. Corrected some of the function arguments to better reflect what they actually accept. Added typescript to the readme. Added a few missing functions.
> Typescript types

- test/types/index.ts
- types/types.d.ts
Syncing with changes from https://github.com/spencermountain/spacetime/issues/97
> Removing internal .d and improving type tests docs.

- test/types/index.ts
- test/types/types.test.ts
- types/types.d.ts
Closes https://github.com/spencermountain/spacetime/issues/131
> Readded the .d prop the the spacetime object and added a couple tests

- test/types/constructor.test.ts
- types/constructors.d.ts
Fixes https://github.com/spencermountain/spacetime/issues/136
> Adding the timezone and options to the static constructors.

- types/constructors.d.ts
- types/index.d.ts
Addresses https://github.com/spencermountain/spacetime/issues/138
> Export interfaces

- src/spacetime.js
- test/toLocalDate.test.js
- types/types.d.ts
Addresses https://github.com/spencermountain/spacetime/issues/185
> 185 dotd not epoch

- README.md
- changelog.md
- contributing.md
- package.json
Couldn't find source for spacetime.how, unfortunately.
> Full credit to Spencer!

- src/methods/compare.js
- test/compare.test.js
- test/world.test.js
- types/types.d.ts
> Update isBetween function to allow for inclusive boolean

- types/types.d.ts
Fixing https://github.com/spencermountain/spacetime/issues/197#issuecomment-644467672
> Fixing a typing issue with every

- src/fns.js
- src/methods/format/_offset.js
Trying to streamline the Timezone offset formatting
> Refactor Timezone offset format

- src/methods/set/set.js
- test/set.test.js
> Allow space before am/pm suffix

- zonefile/iana.js
* see https://www.zeitverschiebung.net/en/timezone/pacific--chatham
> Fix pacific/chatham iana DST change time

- README.md
- src/spacetime.js
- test/toNativeDate.test.js
- types/types.d.ts
Addresses https://github.com/spencermountain/spacetime/issues/288
I've not strong feelings on whether to use the depreciation notice or just add the function in parallel.
> changing toLocalDate to toNativeDate to better explain what the function does

- zonefile/aliases.js
- zonefile/iana.js
There's this city called Asm**e**ra which is sometimes called Asm**a**ra. Both are valid in terms of IANA codes. In this PR, I added "africa/asm**a**ra".
> Added "africa/asmara" zone

- src/spacetime.js
I just checked when silent value pass, it will show silent variable otherwise silent return true. #308
> silent option is not working #308

- src/methods/startOf.js
- test/startOf.test.js
lmk if this was intentionally omitted
> Support subtracting seconds

- src/methods/diff/waterfall.js
- test/diff.test.js
- types/types.d.ts
> Extend `diff()` to also return quarters

- plugins/geo/src/point/IANA-points.js
Hopefully fixes https://github.com/spencermountain/spacetime/issues/364
> Added Asia/Famagusta timezone

- src/spacetime.js
Added a blank space at the beginning of the comment whenever there wasn't one before.
> Added a blank space at the start of each comment.

- package-lock.json
- package.json
- scratch.js
- src/methods/query/03-year.js
Checked for random years and it's working fine.
> week function bug fix

- package-lock.json
- package.json
- test/types/constructor.test.ts
- test/types/index.ts
- test/types/spacetime-static.ts
- test/types/tsconfig.json
- test/types/types.test.ts
This fixes the type tests. I did end up putting the necessary packages as dev-dependencies. Managing it otherwise was becoming difficult.
> Getting the type tests fixed

- README.md
replace outdated function names with the new ones
`.minus` -> `.substract`
`.now` -> `.goto`
> Fix broken example code on README.md

- types/constructors.d.ts
- types/index.d.ts
- types/types.d.ts
> Fix typings

- README.md
the I18n options for plurals was wrong and misled me, so let's correct it :)
> fix README.md about I18n

- .github/workflows/release.yml
> update github workflow

- README.md
- src/methods/format/index.js
- test/format.test.js
- types/constraints.d.ts
#437 
@spencermountain I did my best
> format('sql')
