day/index.js
timezone definition from the map is not exactly same as zonefile's
=> fix: adapt map's timezone to zonefile

.travis.yml, package.json
It is awesome how small is `spacetime`. But to be always small it is good to have regression protect.
[Size Limit](https://github.com/ai/size-limit) is this protection. On every pull request, Travis CI will execute Size Limit. Size Limit will create in memory empty webpack project and add your library there as the dependency. As result, it will calculate the real cost for your uses of add `spacetime`.
If developer will use `process` in wrong way (so webpack will add huge polyfill) or add an unexpected big dependency, Size Limit will tell you in Travis CI.
Materian UI, MobX, PostCSS and Autoprefixer already use it.
@spencermountain what do you think?
=> Add Size Limit

src/input/strParse.js, test/inputs.test.js
Milliseconds are not parsing if iso-string provided as input
```js
let s = spacetime('2017-08-06T09:00:00.000Z')
s.millisecond() === 0 // false
```
=> Fixed iso-string input parsing

test/format.test.js
This test broke for me locally, and it makes sense that it would—the dates seem incorrect.
What's confusing is that both builds (Master and this PR) passed on Travis? Makes me feel like something is wrong with the CI/test setup... ¯\_(ツ)_/¯
=> Fix broken test from f9131db

src/methods.js, src/methods/from.js, test/from.test.js, test/fromNow.test.js
Closes https://github.com/smallwins/spacetime/issues/46
``` javascript
const a = spacetime('November 11, 1999 11:11:11', 'Canada/Eastern');
const b = spacetime('December 12, 2000 12:12:12', 'Canada/Eastern');
a.from(b);
// {
//   diff: {
//     years: -1,
//     months: -1,
//     days: -1,
//     hours: -1,
//     minutes: -1,
//     seconds: -1
//   },
//   rounded: '1 year ago',
//   qualified: '1 year ago',
//   precise: '1 year, 1 month ago'
// }
b.from(a);
// {
//   diff: {
//     years: 1,
//     months: 1,
//     days: 1,
//     hours: 1,
//     minutes: 1,
//     seconds: 1
//   },
//   rounded: 'in 1 year',
//   qualified: 'in 1 year',
//   precise: 'in 1 year, 1 month'
// }
```
``` javascript
const past = spacetime.now()
.subtract(23, 'months')
.subtract(23, 'seconds') …
```
=> Add `from` and `fromNow` methods

src/methods/since.js, test/since.test.js
Month addition and subtraction have a desired 'date' adjusting that keeps 'date' legitimate for the resulting month, this can cause original 'date' been lost when performing 'add 1 month then subtract 1 month' as seen in **getDiff** function.
Eg:
_31 Jan 2019_ adds 1 month resulting _28 Feb 2019_ which when subtracts 1 month resulting _28 Jan 2019_ 
The purpose of 'adding then subtracting' months is just to extract the actual month difference, therefor an **'earlier'** date object clone can be use to calculate the actual difference, then the difference can apply back to the **earlier** date object to keep the original 'date' and also adjusted for the destination month.
The added tests passed along with all other tests.
=> Fix [Issue-89] combination of 'add' and 'subtract' months produce wrong 'date'

.gitignore, scratch.js, src/methods/add.js
seems not to 'walk' on the hours for week addition is the easiest solution, at least keep all tests happy.
there is another bug in since.js cause it outputs something like '6 days 47 hours', which seems also caused by dst crossing, should be fixed in a separate PR
=> fix week calculate issue cause by cross dst

package-lock.json, src/fns.js, src/methods/format/unixFmt.js, test/format.test.js
I think that solution is this method:
```
exports.formatTimezone = function(offset, delimiter){
delimiter = delimiter || ''
const absOffset = Math.abs(offset)
const sign = offset > 0 ? '+' : '-'
return `${sign}${exports.zeroPad(absOffset)}${delimiter}00`
}
```
Note: There are some legacy test failed
=> Fix error about timezone #99

types/types.d.ts
I've noticed there is no type declaration for the since() method, so added a quick on in types.d.ts
Let me know if I've got the signature wrong but think it's more or less correct :)
Thanks for the wonderful library, I use it all the time!
J
=> Add a type declaration for spacetime.since()

types/types.d.ts
Small typescript fix
The api reference here https://observablehq.com/@spencermountain/spacetime-api states that `.month` method can set month with string or number input, but input value in types.d.ts was only of string type
=> fix(*): fix month input type

types/types.d.ts
those 2 methods are definitely returning booleans not the Spacetime object
=> wrong return type fix

types/types.d.ts
It was missing, and now it is not!
=> Added  nearest method to types

types/types.d.ts
I figured out how to split the definitions for the getters and setters. This also allows you to have different documentation for the getter and setter functions.
=> Splitting the function definition for the setters and getters

types/types.d.ts
Hi Spencer, thanks for creating this library. I found .every() missing from the type declaration file, so here I added it.
=> Added .every() to type declaration

test/types/constructor.test.ts, types/constructors.d.ts
Allows ParsableDate like objects to be used in the spacetime constructor
=> Adding a generic ParsableDate constructor definition

src/input/parseTime.js, test/inputs.test.js
Opening a PR to fix an issue we had in our Prod environment, where a UTC timestamp with 6-digit millisecond precision caused the spacetime date to overflow and give us a faulty date. 
e.g. 
`2017-08-06T09:00:00.123456Z`
will give 
`2017-08-06T09:00:01.234Z`
=> fixes non-standard iso-format overflow issue

src/data/caseFormat.js, src/fns.js, src/methods/format/index.js, src/methods/i18n.js, test/i18n.test.js
This PR adds a param `useTitleCase` that can be set as part of `i18n` to turn off the default behavior of returning the day / month names in title case. 
This helps to fully support internationalizing with local date formats -- ex: ex: in French and Spanish, day / month names are typically displayed in  lowercase.
added test case to confirm when `useTitleCase` is set to false, day & month names are all as entered (lower case)
=> support turning off title case for i18n date formatting

types/constructors.d.ts
Quick fix for #255 . I am new to spacetime so I don´t know if anything else is missing here but that is one option I recognized when I tried to use.
=> #255 Added dmy? to SpacetimeConstructorOptions type definitions

src/methods/format/index.js
I noticed that when using curly bracket formats such as `"{day-short} {date-ordinal} {month-short}"` none of the words where capitalized. I added that functionally to `.format()` based on the code above.
I also quickly added 24h versions of the nice and nice-full formats, which I would like to use in one of my sites.
I tested what I changed in a test build as I'm not yet fully sure how to properly write tests and didn't want to make a mess :')
For Comparison this is the current behaviour for curly brackets as of 6.12.2rc:
=> Match caseformat with curly bracket notation and add nice 24h formats

types/types.d.ts
Currently the documentation here: https://github.com/spencermountain/spacetime#timezones specifies that we should be allowed to pass `null` into `Spacetime.goto`, the types do not support this. This commit allows the types to accept a `null` parameter into `Spacetime.goto`
=> Allow `goto` to accept `null`

src/methods/format/index.js, src/methods/format/unixFmt.js, test/format.test.js, types/constraints.d.ts
Add 'millisecond' and 'millisecond-pad' for format(),
Add 'SSS' which means millisecond with pad for unixfmt()
=> Add feature to format milliseconds

zonefile/iana.js
Baku changed from `GMT+5:00` to `GMT+4:00` a few years ago.
See the last entry in the timeline at the bottom of: https://timezonedb.com/time-zones/Asia/Baku
Was brought to my attention by a user in an issue on my react-timezone-select component (https://github.com/ndom91/react-timezone-select/issues/33)
=> fix: update `asia/baku` default offset

src/methods/add.js, test/add.test.js
I initially assumed this bug was down to a more complex issue around DST changes, but it turned out to be caused just by a naming inconsistency between `day` and `date`. 
I'm not sure what the history of "date" vs "day" for the unit name is, but certainly in terms of *intervals*, "day" does make more sense, and I can see why the code that caused this bug *looked* correct.
=> Update naming of 'day' unit to 'date'. Fixes #296.

types/types.d.ts
I _think_ this is correct? Didn't see how an object would be returned in the source and the docs. comment on the above line suggest it's only string.
=> Format function type should only return string

src/methods/since.js, test/since.test.js, types/types.d.ts
This pr extends the return of the `since` method with a new string prop `abbreviated` following the pattern `1y2m3d4m5s`. I've found myself doing it enough times that I think it's a worthy addition.
I realize that `m` for month and minute can be ambiguous, but I think most if not all of the time it should be contextually apparent.
`abbreviated` also deviates from the other properties in that it is always positive regardless of relativity, it's open to discussion but I think it makes sense in context.
I've extended all tests and ensured they pass, and updated the `Since` type. I didn't update the readme because it already only covers two of the existing returns types.
=> [Feature] Extend `since` with `abbreviated`

index.html
Decided to work on issue #306 
Embedded a link into the Github icon on the website so users can also press the image to lead them to the github repo
=> fix issue #306: embed the link into the GitHub icon

types/constructors.d.ts
currently, if you have a type that is one of the `ParsableDate` and optionally undefined, but not specifically a `Date` or undefined (i.e. `Date | undefined`) typescript will not allow the ParsableDate constructor as it does not allow undefined:
```ts
setDate(date?: string) {
const st = spacetime(date)
}
```
> No overload matches this call.
The last overload gave the following error.
Argument of type 'string | undefined' is not assignable to parameter of type 'ParsableDate'.
This PR removes one of the constructors (that is already covered by the ParsableDate constructor), and allows ParsableDate to be undefined
=> Update constructors.d.ts - allow optionally undefined ParsableDate

zonefile/iana.js
Mexico removed the DST for most of their timezones last year. [Approved law on 28/10/2022](https://www.dof.gob.mx/nota_detalle.php?codigo=5670045&fecha=28/10/2022)
This PR updates the `iana.js` file with the updated offsets of the iana database 2023c revision.
=> Fix iana timezones of mexico

package.json
If `nodeResolution` in `tsconfig.json` is set to `Node16` `NodeNext` or `Bundler`, TypeScript (tested on version 5.1.6) will throw error:
```
import spacetime from 'spacetime';
```
```
'spacetime' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'spacetime'. 
```
=> fix types resolution for node16 / bundler

src/methods.js, src/methods/every.js, test/every.test.js, types/types.d.ts
👋 Thanks for taking the time to look at this!
This PR adds a `stepCount` parameter to the `.every()` function, which defaults to 1. 
This is practical for a variety of intervals:
- biannual: every 6 months / 2 quarters
- every 2 weeks
- every 4 years
- every 90 minutes
Happy to address any feedback!
=> Add stepCount parameter for every()

src/methods/format/index.js, test/format.test.js
Fixes issue https://github.com/spencermountain/spacetime/issues/414
The formatting function automatically casts the format to lower case, so a format of `AMPM` is always evaluated as `ampm`. This conditionally casts to lowercase if the format is not `AMPM`
=> Fix AMPM formatting casing.

scripts/updateZonefile.js, zonefile/iana.js
The current dst data in 7.7.0 (and likely earlier) is incorrect due to an issue parsing timezone data for generating iana.js file.
The previous implementation checked the last element on the line from zoneinfo zdump, but actually on linux/osx it's the second to last element. This change simply checks for dst=1 anywhere on the line.
After this change, the timezone data (as an example) for America/New_York correctly uses 2am instead of 4am for DST start.
Closes #430
=> Fix parseLine in updateZoneFile.js to properly detect isdst=1 + update dst data

types/types.d.ts
These methods were incorrectly typed. They don't return a string, they log a string to the console and return the original Spacetime.
=> types: fix log and logYear return types

types/types.d.ts
Fixes the type definition so the two json() functions can overload each other.
=> 435 Fixing type conflict
